import { useEffect, useMemo, useState } from "react";
import {
  TextField,
  InputAdornment,
  CircularProgress,
} from "@mui/material";
import SearchIcon from "@mui/icons-material/Search";

import PageHeader from "../components/common/PageHeader/PageHeader";

import { getAllReports } from "../services/api";
import ReportsTable from "../components/tables/ReportTable";

export default function Reports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [search, setSearch] = useState("");

  useEffect(() => {
    loadReports();
  }, []);

  const loadReports = async () => {
    try {
      setLoading(true);

      const data = await getAllReports();

      setReports(data);
    } catch (err) {
      console.error(err);
      setError("Unable to load reports.");
    } finally {
      setLoading(false);
    }
  };

  const filteredReports = useMemo(() => {
    if (!search.trim()) return reports;

    const query = search.toLowerCase();

    return reports.filter((report) => {
      return (
        report.model.toLowerCase().includes(query) ||
        report.prompt_name.toLowerCase().includes(query) ||
        report.dataset_name.toLowerCase().includes(query) ||
        report.health_status.toLowerCase().includes(query) ||
        report.report_id.toString().includes(query)
      );
    });
  }, [reports, search]);

  return (
    <div className="space-y-8 p-8">
      <PageHeader
        title="Reports"
        subtitle="Browse all evaluation reports generated by EvalGuard AI."
        actions={
          <div className="w-full md:w-96">
            <TextField
              fullWidth
              size="small"
              placeholder="Search reports..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              InputProps={{
                startAdornment: (
                  <InputAdornment position="start">
                    <SearchIcon />
                  </InputAdornment>
                ),
              }}
            />
          </div>
        }
      />

      {loading && (
        <div className="flex h-80 items-center justify-center">
          <CircularProgress />
        </div>
      )}

      {!loading && error && (
        <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-6 text-red-400">
          {error}
        </div>
      )}

      {!loading && !error && (
        <ReportsTable reports={filteredReports} />
      )}
    </div>
  );
}